# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'DLSuit' do
pod 'DLSuit', :git => 'https://github.com/danigarciaalva/DLSuit.git'
end

target 'Tests' do

end

